"""add holiday work time columns

Revision ID: 605c73603166
Revises: b38819b0556e
Create Date: 2025-07-11 09:57:37.621060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605c73603166'
down_revision = 'b38819b0556e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_holiday_work', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('holiday_start_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('holiday_start_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('holiday_end_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('holiday_end_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('holiday_work_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('holiday_total_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_column('holiday_total_minutes')
        batch_op.drop_column('holiday_work_minutes')
        batch_op.drop_column('holiday_end_minute')
        batch_op.drop_column('holiday_end_hour')
        batch_op.drop_column('holiday_start_minute')
        batch_op.drop_column('holiday_start_hour')
        batch_op.drop_column('is_holiday_work')

    # ### end Alembic commands ###
