"""Add president checked flags

Revision ID: 6df7b0ea0dc5
Revises: c6d44d8460bd
Create Date: 2025-07-16 11:49:55.184607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df7b0ea0dc5'
down_revision = 'c6d44d8460bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('president_checked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_column('president_checked')

    # ### end Alembic commands ###
