"""Add paid_leave_minutes

Revision ID: b38819b0556e
Revises: 
Create Date: 2025-07-08 21:40:12.434790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38819b0556e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_leave_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_column('paid_leave_minutes')

    # ### end Alembic commands ###
