"""Add manager and director check flags

Revision ID: c6d44d8460bd
Revises: 605c73603166
Create Date: 2025-07-16 10:50:48.648073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d44d8460bd'
down_revision = '605c73603166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_checked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('director_checked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_column('director_checked')
        batch_op.drop_column('manager_checked')

    # ### end Alembic commands ###
